# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: bionic
services:
  - docker
language: generic 
env:
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="melodic" PRERELEASE=true
    - ROS_DISTRO="noetic"
    - ROS_DISTRO="noetic" PRERELEASE=true
matrix:
  allow_failures:
    # Run docker-based ROS prerelease test http://wiki.ros.org/bloom/Tutorials/PrereleaseTest Because we might not want to run prerelease test for all PRs, it's omitted from pass-fail criteria.
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
    - env: ROS_DISTRO="noetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config -b master
script:
  - source .ci_config/travis.sh
