%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-pybind11-catkin
Version:        2.4.3
Release:        1%{?dist}
Summary:        ROS pybind11_catkin package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       numpy
Requires:       python-devel
BuildRequires:  ros-melodic-catkin

%description
The pybind11 package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Mon Dec 23 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.4.3-1
- Autogenerated by Bloom

* Tue Jan 15 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-6
- Autogenerated by Bloom

* Tue Jan 15 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-5
- Autogenerated by Bloom

* Mon Jan 14 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-4
- Autogenerated by Bloom

* Mon Jan 14 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-3
- Autogenerated by Bloom

* Mon Jan 14 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-2
- Autogenerated by Bloom

* Tue Jan 08 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-1
- Autogenerated by Bloom

* Sat Jan 05 2019 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.4-0
- Autogenerated by Bloom

* Thu Jul 12 2018 Vladimir Ivan <v.ivan@ed.ac.uk> - 2.2.3-0
- Autogenerated by Bloom

